### ISSUE TITLE
5.1.0使用algolia搜索问题

### ISSUE THREAD

**Issue by panoshu** [iissnan/hexo-theme-next#1084]
### Expected behavior (预期行为)

搜索菜单可点击且弹出搜索页面
### Actual behavior (实际行为)

搜索菜单在菜单栏的居中位置，而且点击无反应
### Steps to reproduce the behavior (重现步骤)

主题配置文件设置
algolia_search:
  enable: true
站点配置文件设置
algolia:
  applicationID: '**_'
  apiKey: '**_'
  adminApiKey: '**_'
  indexName: '**_'
  chunkSize: 5000
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release ✔ 
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces ✔

**Comment by liujiayi771** [comment]
我也有这个问题啊，不知道怎么解决

**Comment by iissnan** [comment]
@panoshu 主题配置文件里的 `applicationID`, `apiKey` 和 `indexName` 都必须配置。另外，能打开浏览器的 Console 看下是否有什么错误没有

**Comment by ehlxr** [comment]
我的点击后：http://ehlxr.me/undefined
![image](https://cloud.githubusercontent.com/assets/11313370/19471578/7a8b2aba-9556-11e6-8254-625eeb397d76.png)

Console报错：
![image](https://cloud.githubusercontent.com/assets/11313370/19471626/b0e9c0bc-9556-11e6-8079-b458a5b1e3f0.png)

**Comment by zlc1994** [comment]
@ehlxr 这是因为hexo-algolia的作者并没有把`post.path`进行index，所以`data.path`是undefined，你可以自己修改hexo-algolia里面的command.js，把`path`加进去，重新index。

**Comment by ehlxr** [comment]
3Q，我试试

**Comment by innote** [comment]
大家如果遇到同樣問題， 請install `npm install hexo-algolia@0.2.0`， 然後在站点找到`package.json`， 把裏面的hexo-algolia， 換成 `"hexo-algolia": "^0.2.0"`。 

再重新index， 就可以了。

**Comment by shevonwang** [comment]
@zlc1994 请问要怎么加path呢

**Comment by innote** [comment]
@shevonwang 去`node_modules/hexo-algolia/lib`， 加`path`。

```
var storedPost = _.pick(data, ['title', 'date', 'slug', '**path**', 'content', 'excerpt', 'objectID']);
```

**Comment by xxllll** [comment]
@innote 请问为何我用了0.2.0以及加了路径，仍然无法点按搜索。。

**Comment by lovingzw** [comment]
之前配置成功了，链接也正常。但是今天又404了...

**Comment by innote** [comment]
@xxllll 和 @lovingzw 你們還是要再index多一次呀！！！！

**Comment by lovingzw** [comment]
发现是在 algolia indice设置的问题。解决了，thanks! @innote

**Comment by Southhill** [comment]
我在hexo-algolia0.1.1的版本上修改了comand.js文件(第30行的位置，添加了‘path’),之后重新运行了命令'hexo algolia',将修改后的版本部署好之后，搜索出来的链接点击果然跳转到正确的位置了。

**Comment by consen** [comment]
https://github.com/iissnan/hexo-theme-next/blob/master/layout/_partials/header.swig#L54-L56

```
          {% elseif config.search %}
            <a href="javascript:;" class="popup-trigger">
          {% endif %}
```

除了在主题配置文件中配置:

```
algolia_search:
  enable: true
```

难道还需要在站点配置文件中添加'search'字段？

```
search: true
```

**Comment by iissnan** [comment]
@consen master 分支上这个地方的判断加上了 `theme.algolia_search.enable`

```
{% elseif config.search || theme.algolia_search.enable %}
        <a href="javascript:;" class="popup-trigger">
{% endif %}
```

**Comment by hy08** [comment]
# Theme version
version: 5.1.0
这个版本中，var storedPost = _.pick(data, ['title', 'date', 'slug', 'path', 'content', 'excerpt', 'objectID']);的确应该是这样，而我的原先是var storedPost = _.pick(data, ['title', 'date', 'slug',  'content', 'excerpt', 'permalink']); 因此不仅要添加path字段，还要修改最后的permalink字段

**Comment by WardLIN** [comment]
@iissnan 我发现搜索出来的条目的链接是undefined，查看了一下algolia官网返回的json里并没有包含path对象，请问是什么原因？（hexo-algolia是0.2.0版本的了，common.js配置正确）

**Comment by iissnan** [comment]
What attributes did you get?

NexT release 5.1.0 should be compatible with hexo-algolia both 0.2.0 and 0.1.0.

**Comment by WardLIN** [comment]
@iissnan I got attributes such as title,slug,contentStrip,objectID,_highlightResult,_rankingInfo but without path,so 'data.path' is undefined!
![1](https://cloud.githubusercontent.com/assets/21731696/24080300/117fc87a-0cd7-11e7-8682-ec228baca369.png)

**Comment by kitianFresh** [comment]
I got the same problem too, Algolia can't response a correct urls for search results after I add 'path' and modify hexo-algolia to 0.2.0

**Comment by longhai123** [comment]
我遇到的一个情况是一开始配置了swiftype_key，然后更改成local或者algolia的方式都不行，也找了好久，只需要把站点配置文件里面的swiftype_key选项去掉就好了。看看有没有能够给一些人提供思路。

**Comment by Yelloboy** [comment]
出现搜索框搜索不到任何东西，请教一下

**Comment by thyeun** [comment]
@Yelloboy, 我可以具體的了解你的問題嗎？， 因爲搜索框搜索不到， 可以是因爲你的布置不完善/不對。

**Comment by forsunwell** [comment]
@thyeun 请问下，我这里出现如下错误，是什么原因？
`INFO  [Algolia] Index cleared.
INFO  [Algolia] Starting indexation...

E:\code\hexo\node_modules\hexo-algolia\lib\command.js:99
        throw err;
        ^
AlgoliaSearchNetworkError: connect ETIMEDOUT 103.6.130.169:443
    at ClientRequest.error (E:\code\hexo\node_modules\algoliasearch\src\server\builds\node.js:228:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

Next版本：
`# Theme version
version: 5.1.4`

软件包版本：
`tnpm install hexo-algolia@0.2.0`

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by ivan-nginx** [comment]
I don't know what's happen here, but it seems this is not solved or wrong fixed issue and @thyeun trying to do best things here.

**Comment by thyeun** [comment]
@innote 也是我的號， 在這裏先說聲對不起， @iissnan 可能已經不是這個project的站長了， 因爲我不在contributor list所以在這裏的解答是不給其他人接受的，我也不會再給任何解答。

-----------------------------------------------------------------------------------------------------------------------------------------
@innote also is my account, first of all, i'm sorry everyone, @iissnan might be not the project leader anymore, and because i'm not in the contributor list, i should not given any temporary solution here, it might not accepted by others, so for now on, i wont answering any topic that related with this project.

----------------------------------------------------------------------------------------------------------------------------------------
Peace out!!!! @ivan-nginx pls don't mention my name here, and i'm sure you can provided better solid solution for the user.  thanks!

**Comment by sli1989** [comment]
@forsunwell The use of Algolia Search maybe updated. Can you follow [this instruction ](https://github.com/sli1989/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md)to reproduce your problem?
Then, the detailed steps needs too.

**Comment by aline2013** [comment]
@MoBenw 
同样出现`http://yoursite.com/`这个问题，现已解决

1. 原本5.1.0就出现改问题，但一直没注意修改。其实，修改方法：就是楼上 @zlc1994 所说，缺少path，修改完command.js后，要重新hexo alglia(最好重新hexo algolia之前最好把algolia网站上indices模块的index缓存清空)

2. 升级博客版本后，hexo: 3.7.0,  next: 6.4.0，hexo-algolia: ^1.2.5
并依照[Algolia Search for NexT](https://github.com/theme-next/theme-next-algolia-instant-search)更新了主题下的theme-next-algolia-instant-search。
此时发现，新的theme-next-algolia-instant-search已经支持permalink，这个permalink就是你在站点_comfig.yml下配置的。所以，此时你需要做的仅仅是：重新hexo alglia(最好重新hexo algolia之前最好把algolia网站上indices模块的index缓存清空)

如下，我的站点_comfig.yml
```
url: https://www.aline2013.com
root: /
permalink: article/:title.html
permalink_defaults: article/:title.html
```
那么，跳转的路径是 https://www.aline2013.com/article/blog-inhance_deep.html

**Comment by monkeyip** [comment]
> @MoBenw
> 同样出现`http://yoursite.com/`这个问题，现已解决
> 
> 1. 原本5.1.0就出现改问题，但一直没注意修改。其实，修改方法：就是楼上 @zlc1994 所说，缺少path，修改完command.js后，要重新hexo alglia(最好重新hexo algolia之前最好把algolia网站上indices模块的index缓存清空)
> 2. 升级博客版本后，hexo: 3.7.0,  next: 6.4.0，hexo-algolia: ^1.2.5
>    并依照[Algolia Search for NexT](https://github.com/theme-next/theme-next-algolia-instant-search)更新了主题下的theme-next-algolia-instant-search。
>    此时发现，新的theme-next-algolia-instant-search已经支持permalink，这个permalink就是你在站点_comfig.yml下配置的。所以，此时你需要做的仅仅是：重新hexo alglia(最好重新hexo algolia之前最好把algolia网站上indices模块的index缓存清空)
> 
> 如下，我的站点_comfig.yml
> 
> ```
> url: https://www.aline2013.com
> root: /
> permalink: article/:title.html
> permalink_defaults: article/:title.html
> ```
> 那么，跳转的路径是 https://www.aline2013.com/article/blog-inhance_deep.html

我的hexo都是3.8.0了，也是出现http://yoursite.com/这个问题，而且我也更改了站点配置文件下的rul为自己的博客地址，但是结果还是不好使，顺便问下hexo algolia之前最好把algolia网站上indices模块的index缓存清空，这个操作在哪做啊。

**Comment by monkeyip** [comment]
> @Yelloboy, 我可以具體的了解你的問題嗎？， 因爲搜索框搜索不到， 可以是因爲你的布置不完善/不對。

你好，我也是同样的问题，这个algolia经常不好使，前段时间刚弄好，发现搜不到最开始第一篇文章，但是能搜到后面的，我很疑惑，后面新增文章也都搜不到，我怀疑是没有加index的原因。

然后我就重新hexo algolia了，也都正常，但是出现以下提示：

INFO  Start processing                                                                                                                                                       INFO  [Algolia] Identified 0 posts to index.                                                                                                                                 INFO  [Algolia] Clearing index...                                                                                                                                            INFO  Files loaded in 2.39 s                                                                                                                                                 INFO  0 files generated in 405 ms                                                                                                                                            INFO  [Algolia] Index cleared.                                                                                                                                               INFO  [Algolia] Starting indexation...                                                                                                                                       INFO  [Algolia] Import done.                                                                                                                                                 INFO  [Algolia] Highlight tag definition success.
--

很明显这次更新0条index了，直接导致我在博客里打开搜索一条都搜不到，搜索框右下角本该有的algolia图标也没了。

![image](https://user-images.githubusercontent.com/33145980/56965894-ba812800-6b90-11e9-9906-46ebdfee6200.png)

 还请帮忙解答下呢？谢谢。
--
