### ISSUE TITLE
hexo s --debug 开启服务报错:no such file or directory, open hexo/themes/hexo-theme-next-5.0.1/layout/_scripts/schemes/.swig'

### ISSUE THREAD

**Issue by zhanghonged** [iissnan/hexo-theme-next#1212]
之前一直正常，今天发布新文章，结果出现这个报错：

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/pack/baiduyun/Hexo/hexo/themes/hexo-theme-next-5.0.1/layout/_scripts/schemes/.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)

麻烦帮忙看看，Thanks.

**Comment by Neveryu** [comment]
难道是因为升级新版本的问题？

**Comment by iissnan** [comment]
没有识别到 Scheme，确认下你的配置。

**Comment by zhanghonged** [comment]
不知道什么问题，版本升级后问题就解决了

**Comment by gdutxiaoxu** [comment]
我也遇到这个问题了，不知道怎么解决

**Comment by gdutxiaoxu** [comment]
@zhanghonged 你是怎样进行 版本升级的，最新版本不是才到5.0.1吗

**Comment by zhanghonged** [comment]
@gdutxiaoxu 之前是用老版本，升级到5.0.1就好了

**Comment by roc-wong** [comment]
请检查_config.yml，如果配置中出现例如 ****:*** 这样格式的配置，请将其更正为 
***: *** 
例如 authoricon:heart -> authoricon: heart

**Comment by zzl1428377909** [comment]
老哥，我也是这种情况，Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\hexo\themes\next\layout\_partials\page-header.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.ret.load (D:\hexo\node_modules\hexo\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at compileFile (D:\hexo\node_modules\hexo\node_modules\swig\lib\swig.js:695:31)
    at Object.eval [as tpl] (eval at <anonymous> (D:\hexo\node_modules\hexo\node_modules\swig\lib\swig.js:498:13), <anonymous>:244:18)
    at compiled (D:\hexo\node_modules\hexo\node_modules\swig\lib\swig.js:619:18)
    at _compiled (D:\hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\hexo\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (D:\hexo\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\hexo\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:733:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

你怎么解决的啊

**Comment by WangHuiying** [comment]
http://jianbing.github.io/2016/04/30/set-up-next/ 这篇博客写的比较详细

**Comment by weijihong** [comment]
我的解决是我在侧边栏加入social时候，输入微博后的冒号是中文冒号，改成英文就好

**Comment by wkq278276130** [comment]
升级到最新版本后hexo generate的时候报错了，看一下debug日志。

原因在报错日志里找见了，是Social Links配置出现的问题，希望开发人员看一下是不是这个问题 @iissnan 

bad indentation of a mapping entry at line 122, column 3:\n      GitHub: https://github.com/wkq27 ... \n      ^","name":"YAMLException"

"message":"bad indentation of a mapping entry at line 123, column 3:\n      E-Mail: mailto:gmail@gmail.com\n      ^","name":"YAMLException","stack":"YAMLException: bad indentation of a mapping entry at line 123, column 3:\n

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
