### ISSUE TITLE
目前似乎不支持Hexo3

### ISSUE THREAD

**Issue by destinyliu** [iissnan/hexo-theme-next#1225]
### Expected behavior (预期行为)

希望能支持Hexo3
### Actual behavior (实际行为)

目前
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /Users/fengmian/workspaces/thinking-work/hexo-test/themes/next/layout/layout.ejs:9
    7|         <section id="main"><%- body %></section>
    8|         <% if (theme.sidebar && theme.sidebar !== 'bottom'){ %>
 >> 9|           <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %>
    10|         <% } %>
    11|       </div>
    12|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

/Users/fengmian/workspaces/thinking-work/hexo-test/themes/next/layout/_partial/sidebar.ejs:2
    1| <aside id="sidebar"<% if (theme.sidebar === 'bottom'){ %> class="outer"<% } %>>
 >> 2|   <% theme.widgets.forEach(function(widget){ %>
    3|     <%- partial('_widget/' + widget) %>
    4|   <% }) %>
    5| </aside>

Cannot read property 'forEach' of undefined
    at eval (eval at <anonymous> (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:242:14), <anonymous>:30:185)
    at eval (eval at <anonymous> (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:242:14), <anonymous>:30:342)
    at /Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/theme/view.js:50:21)
    at /Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/plugins/helper/partial.js:38:21
    at Object.fragmentCache (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/plugins/helper/fragment_cache.js:9:30)
    at Object.wrapper [as fragment_cache] (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.4.16.6@lodash/lodash.js:4962:19)
    at Object.partial (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/plugins/helper/partial.js:37:19)
    at Object.wrapper (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.4.16.6@lodash/lodash.js:4962:19)
category_map:
    at eval (eval at <anonymous> (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:242:14), <anonymous>:30:443)
    at eval (eval at <anonymous> (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:242:14), <anonymous>:30:890)
    at /Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.1.0.0@ejs/lib/ejs.js:255:15
    at _compiled (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/theme/view.js:127:30)
    at View.render (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/theme/view.js:29:15)
    at /Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.2.2@hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/fengmian/workspaces/thinking-work/hexo-test/node_modules/.3.4.6@bluebird/js/release/async.js:138:16)

^CINFO  See you again

**Comment by tjuzl** [comment]
我最近重新安装了 Hexo ，默认应该是最新版。使用 NexT 主题，一切都正常。

**Comment by iissnan** [comment]
NexT 支持 Hexo 3。从你的错误 log 上看，里面有 ejs 文件，但 NexT 使用的是 Swig，这个 ejs 是自己新增的？

**Comment by imkratos** [comment]
楼主，我以前也遇到了各种奇葩的错误,我重新安装了nodejs的稳定版本，重新安装了hexo的版本，重新安装了插件。以前我经常遇到的问题就是nodejs更新版本之后，hexo各种问题，各种报错。

**Comment by Johnsonzcode** [comment]
可能是因为插件版本被降级或者升级了，前版本中用swig，改变后用ejs了
