### ISSUE TITLE
报错YAMLException: end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by lan2720** [iissnan/hexo-theme-next#1235]
Hi all,
更新之后报这个错，
```

YAMLException: end of the stream or a document separator is expected at line 3, column 1:
    menu:
    ^
    at generateError (/Users/lan2720/Documents/lan2720.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/Users/lan2720/Documents/lan2720.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readDocument (/Users/lan2720/Documents/lan2720.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1498:5)
    at loadDocuments (/Users/lan2720/Documents/lan2720.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
    at Object.load (/Users/lan2720/Documents/lan2720.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
    at Hexo.yamlHelper (/Users/lan2720/Documents/lan2720.github.io/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/lan2720/Documents/lan2720.github.io/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

和这个
```
Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/lan2720/Documents/lan2720.github.io/themes/next/layout/_scripts/schemes/.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.ret.load (/Users/lan2720/Documents/lan2720.github.io/node_modules/swig/lib/loaders/filesystem.js:55:15)
    at compileFile (/Users/lan2720/Documents/lan2720.github.io/node_modules/swig/lib/swig.js:695:31)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/lan2720/Documents/lan2720.github.io/node_modules/swig/lib/swig.js:498:13), <anonymous>:299:18)
    at compiled (/Users/lan2720/Documents/lan2720.github.io/node_modules/swig/lib/swig.js:619:18)
    at Object.render (/Users/lan2720/Documents/lan2720.github.io/node_modules/swig/lib/swig.js:525:41)
    at Hexo.swigRenderer (/Users/lan2720/Documents/lan2720.github.io/node_modules/hexo/lib/plugins/renderer/swig.js:35:15)
    at Hexo.tryCatcher (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/lan2720/Documents/lan2720.github.io/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/lan2720/Documents/lan2720.github.io/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
请问是怎么回事啊？如何解决？感谢！

**Comment by yhhwpp** [comment]
是发布的的时候报错吗？

**Comment by lan2720** [comment]
@yhhwpp 最后经过很多步，弄好了= =

**Comment by geelaro** [comment]
我也遇到这个问题了，请问是什么原因？

**Comment by shursulei** [comment]
请问你解决的原因和方法是什么

**Comment by stevenjoezhang** [comment]
@geelaro @shursulei 检查`_config.yml`是否出现错误语法
请使用新版：https://github.com/theme-next/hexo-theme-next

**Comment by lddsb** [comment]
解决方案应该就是在`md`文件前面添加说明
```
---
title: your title
date: 2019-12-07 14:32:46
tags:
- something
keywords:
- some
- thing
- something
description: your description
---
```

**Comment by DocWho22** [comment]
我也遇到这个问题了
