### ISSUE TITLE
hexo d 发布报错  inflate:data stream error (unkonw compression method)

### ISSUE THREAD

**Issue by yhhwpp** [iissnan/hexo-theme-next#1236]
hexo 发布的时候报下面错误，改如何解决
```
$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
error: inflate: data stream error (unknown compression method)
fatal: failed to read object 3f596f94ad4461bb7dbfe232dcda1f4cac011152: Invalid argument
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: error: inflate: data stream error (unknown compression method)
fatal: failed to read object 3f596f94ad4461bb7dbfe232dcda1f4cac011152: Invalid argument

    at ChildProcess.<anonymous> (F:\workplace\hexo\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (F:\workplace\hexo\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
FATAL error: inflate: data stream error (unknown compression method)
fatal: failed to read object 3f596f94ad4461bb7dbfe232dcda1f4cac011152: Invalid argument

Error: error: inflate: data stream error (unknown compression method)
fatal: failed to read object 3f596f94ad4461bb7dbfe232dcda1f4cac011152: Invalid argument

    at ChildProcess.<anonymous> (F:\workplace\hexo\blog\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (F:\workplace\hexo\blog\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

```

**Comment by yhhwpp** [comment]
已解决，删除了.deploy_git文件夹，重新发布就正常了

**Comment by yhhwpp** [comment]
fix  #1263

**Comment by yhhwpp** [comment]
fix  #1236
