### ISSUE TITLE
_custom/custom.styl文件出现问题

### ISSUE THREAD

**Issue by fred1653** [iissnan/hexo-theme-next#1238]
### 出现的问题
重新安装hexo和next（git clone和5.1都有问题），默认主题可以显示，但是换成next后CSS就无法显示，`hexo g`正常但是`hexo s`后就访问就出现问题。

```
hoo@DESKTOP-0632OQT E:\HJN\hexo                                                 
$ hexo s                                                                        
INFO  Start processing                                                          
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.          
ERROR Asset render failed: css/main.css                                         
TypeError: E:\HJN\hexo\themes\next\source\css\main.styl:46:1                    
   42|                                                                          
   43| // Custom Layer                                                          
   44| // --------------------------------------------------                    
   45| @import "_custom/custom";                                                
   46|                                                                          
-------^                                                                        
                                                                                
Path must be a string. Received undefined                                       
                                                                                
    at assertPath (path.js:7:11)                                                
    at extname (path.js:887:5)                                                  
    at new SourceMapper (E:\HJN\hexo\node_modules\stylus\lib\visitor\sourcemappe
r.js:41:7)                                                                      
    at Renderer.render (E:\HJN\hexo\node_modules\stylus\lib\renderer.js:94:9)   
    at Hexo.module.exports (E:\HJN\hexo\node_modules\hexo-renderer-stylus\lib\re
nderer.js:53:6)                                                                 
    at Hexo.tryCatcher (E:\HJN\hexo\node_modules\bluebird\js\release\util.js:16:
23)                                                                             
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\hoo\AppData\Roaming\n
pm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), 
<anonymous>:13:39)                                                              
    at E:\HJN\hexo\node_modules\hexo\lib\hexo\render.js:61:21                   
    at tryCatcher (E:\HJN\hexo\node_modules\bluebird\js\release\util.js:16:23)  
    at Promise._settlePromiseFromHandler (E:\HJN\hexo\node_modules\bluebird\js\r
elease\promise.js:510:31)                                                       
    at Promise._settlePromise (E:\HJN\hexo\node_modules\bluebird\js\release\prom
ise.js:567:18)                                                                  
    at Promise._settlePromise0 (E:\HJN\hexo\node_modules\bluebird\js\release\pro
mise.js:612:10)                                                                 
    at Promise._settlePromises (E:\HJN\hexo\node_modules\bluebird\js\release\pro
mise.js:691:18)                                                                 
    at Async._drainQueue (E:\HJN\hexo\node_modules\bluebird\js\release\async.js:
138:16)                                                                         
    at Async._drainQueues (E:\HJN\hexo\node_modules\bluebird\js\release\async.js
:148:10)                                                                        
    at Immediate.Async.drainQueues (E:\HJN\hexo\node_modules\bluebird\js\release
\async.js:17:14)                                                                
    at runCallback (timers.js:637:20)                                           
    at tryOnImmediate (timers.js:610:5)                                         
    at processImmediate [as _immediateCallback] (timers.js:582:5)               
INFO  Farewell                                                                  
终止批处理操作吗(Y/N)?                                                                  
```

机器配置：
```
$ hexo -version
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 10.0.14931 win32 x64
http_parser: 2.7.0
node: 7.0.0
v8: 5.4.500.36
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 51
openssl: 1.0.2j
```

**Comment by iissnan** [comment]
看下 `source/css/_custom/custom.styl` 文件是否存在。

从错误信息上看不像是这个文件的问题。

**Comment by fred1653** [comment]
`hexo\themes\next\source\css\_custom.styl`文件
```
// Custom styles.

```

使用`hexo g --debug`为报错，之后再使用`hexo s`

```
$ hexo s
[BS] Access URLs:
 --------------------------------------
          UI: http://localhost:3001
 --------------------------------------
 UI External: http://49.123.117.50:3001
 --------------------------------------
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
ERROR Asset render failed: css/main.css
TypeError: E:\HJN\hexo\themes\next\source\css\main.styl:46:1
   42|
   43| // Custom Layer
   44| // --------------------------------------------------
   45| @import "_custom/custom";
   46|
-------^

Path must be a string. Received undefined

    at assertPath (path.js:7:11)
    at extname (path.js:887:5)
    at new SourceMapper (E:\HJN\hexo\node_modules\stylus\lib\visitor\sourcemapper.js:41:7)
    at Renderer.render (E:\HJN\hexo\node_modules\stylus\lib\renderer.js:94:9)
    at Hexo.module.exports (E:\HJN\hexo\node_modules\hexo-renderer-stylus\lib\renderer.js:53:6)
    at Hexo.tryCatcher (E:\HJN\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\hoo\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at E:\HJN\hexo\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (E:\HJN\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HJN\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (E:\HJN\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (E:\HJN\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (E:\HJN\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (E:\HJN\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (E:\HJN\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (E:\HJN\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```
访问localhost 4000，无CSS， 访问localhost 3001 进入Browsersync 界面。 同样，部署到git上之后也是无CSS的。
在chrome中查看css资源，显示`main.css?v=5.1.0`为空。

**Comment by mcknote** [comment]
我也遇到相同問題了，暫時用以前生成的 main.css 取代頂著……

**Comment by mcknote** [comment]
`$ hexo v
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 16.3.0 darwin x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
`

另外執行 `hexo v` 時會出現 `DTraceProvider` 相關錯誤。

**Comment by nickbuddendotcom** [comment]
```
# Stylus
stylus:
  compress: false
  # sourcemaps:
  #   comment: true
  #   inline: true
  #   sourceRoot: ''
  #   basePath: .
```

Commenting out sourcemaps works for me.

**Comment by mcknote** [comment]
Problem solved by using Travis-CI and having the environment set to node.js 0.10.
