### ISSUE TITLE
配置algolia，跟新algolia失败

### ISSUE THREAD

**Issue by movie0125** [iissnan/hexo-theme-next#1293]
### Expected behavior (预期行为)
algolia:
  applicationID: 'applicationID'
  apiKey: 'apiKey'
  adminApiKey: 'adminApiKey'
  indexName: 'indexName'
  chunkSize: 5000

### Actual behavior (实际行为)
algolia:
  applicationID: "xxxx"
  apiKey: "xxxxx"
  adminApiKey: "xxxxx"
  indexName: "xxxxx"
  chunkSize: 5000

### Steps to reproduce the behavior (重现步骤)
npm install --save hexo-algolia
配置站点文件，新增配置项
更新hexo algolia

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
INFO  Start processing
INFO  [Algolia] Identified 0 posts to index.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (/home/movie/git/hexoblog/node_modules/algoliasearch/src/AlgoliaSearchCore.js:45:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (/home/movie/git/hexoblog/node_modules/algoliasearch/src/AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/node.js:80:23)
    at algoliasearch (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/node.js:69:10)
    at Hexo.<anonymous> (/home/movie/git/hexoblog/node_modules/hexo-algolia/lib/command.js:68:22)
    at emitNone (events.js:67:13)
    at Hexo.emit (events.js:166:7)
    at /home/movie/git/hexoblog/node_modules/hexo/lib/hexo/index.js:405:10
    at tryCatcher (/home/movie/git/hexoblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:636:18)
    at MappingPromiseArray.PromiseArray._resolve (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/home/movie/git/hexoblog/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/movie/git/hexoblog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/movie/git/hexoblog/node_modules/bluebird/js/release/async.js:148:10)
FATAL Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (/home/movie/git/hexoblog/node_modules/algoliasearch/src/AlgoliaSearchCore.js:45:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (/home/movie/git/hexoblog/node_modules/algoliasearch/src/AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/node.js:80:23)
    at algoliasearch (/home/movie/git/hexoblog/node_modules/algoliasearch/src/server/builds/node.js:69:10)
    at Hexo.<anonymous> (/home/movie/git/hexoblog/node_modules/hexo-algolia/lib/command.js:68:22)
    at emitNone (events.js:67:13)
    at Hexo.emit (events.js:166:7)
    at /home/movie/git/hexoblog/node_modules/hexo/lib/hexo/index.js:405:10
    at tryCatcher (/home/movie/git/hexoblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:636:18)
    at MappingPromiseArray.PromiseArray._resolve (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise_array.js:125:19)
    at MappingPromiseArray._promiseFulfilled (/home/movie/git/hexoblog/node_modules/bluebird/js/release/map.js:101:18)
    at Promise._settlePromise (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/movie/git/hexoblog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/movie/git/hexoblog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/movie/git/hexoblog/node_modules/bluebird/js/release/async.js:148:10)

**Comment by geekrainy** [comment]
检查配置是否写全，注意配置字段无引号。

**Comment by movie0125** [comment]
多谢，问题已经解决
配置应该是写到  hexo/_configxxx
结果我写到了  hexo/theme/next/_configxx

重新来了一次，就好了。

**Comment by BQSQ** [comment]
algolia:
  applicationID: 'applicationID'
  apiKey: 'apiKey'
  adminApiKey: 'adminApiKey'
  indexName: 'indexName'
  chunkSize: 5000

我的问题是子项目没有进行缩进，导致配置无法读取。
将子项配置缩进如上就可以了

**Comment by BeethovenVirus** [comment]
遇到了同样的问题
![image](https://user-images.githubusercontent.com/28602460/27001616-2ef2ce5a-4e01-11e7-96bd-d10e0ae50e31.png)

applicationID 能找到，apiKey 却提示找不到，还不知道原因在哪儿。缩进方面已经检查了。

**Comment by realzsy** [comment]
在站点文件配置了，也缩进了，还是报错。

**Comment by dongcj** [comment]
同样的问题，都检查了，还是报错，提示找不到 apiKey

**Comment by pengbd3** [comment]
@dongcj  `hexo-algolia1.1.0` 为了安全起见需要导入API_KEY,详见官方说明
[https://github.com/oncletom/hexo-algolia/tree/20f6ecfde2b3348c2fba5ffc3963cc1ba7d2e3cb#api-key](url)

**Comment by qujingpeng** [comment]
在终端输入export HEXO_ALGOLIA_INDEXING_KEY=你的api_key     
在cmd 命令中输入吗  还是在其他地方

**Comment by pengbd3** [comment]
可以，推荐你使用`Git Bash`

**Comment by qujingpeng** [comment]
已解决 window环境下  应该是在终端输入 set  HEXO_ALGOLIA_INDEXING_KEY=你的api_key  
而不是  export

**Comment by changhr2013** [comment]
使用export HEXO_ALGOLIA_INDEXING_KEY语句后运行hexo algolia提示
AlgoliaSearchError: Invalid Application-ID or API key
  at success (C:\Users\changhr2013\blog\node_modules\algoliasearch\src\AlgoliaSearchCore.js:351:32)
  at process._tickCallback (internal/process/next_tick.js:109:7)
意思是说我的key无效，NexT主题5.1.2版本，key都是直接复制过来的，目前无解。
