### ISSUE TITLE
更新到v0.3.0rc1,用hexo g命令出现解析错误

### ISSUE THREAD

**Issue by XhstormR** [iissnan/hexo-theme-next#13]
这是package.json中的信息
```
{
  "name": "hexo-site",
  "version": "2.8.3",
  "private": true,
  "dependencies": {
    "hexo-renderer-ejs": "*",
    "hexo-renderer-stylus": "*",
    "hexo-renderer-marked": "*"
  }
}
```
这是debug.log中的信息
```
date: "2015-02-17 10:27:18.709"
argv: "d:\\Node\\node.exe d:\\Node\\npm-global\\node_modules\\hexo\\bin\\hexo g"
os: Windows_NT 6.3.9600 win32 x64
versions:
  http_parser: "2.3"
  node: 0.12.0
  v8: 3.28.73
  uv: 1.0.2
  zlib: 1.2.8
  modules: "14"
  openssl: 1.0.1l
  hexo: 2.8.3
-------
ParseError: d:/hexo/themes/next/source/css/_section/sidebar.styl:121
   117|     }
   118|   }
   119| 
   120|   }
 > 121| 
   122| .social-info {
   123|   margin-top: 20px;
   124| }

unexpected "outdent"

    at Parser.error (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\parser.js:255:11)
    at Parser.stmt (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\parser.js:773:32)
    at Parser.statement (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\parser.js:645:21)
    at Parser.parse (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\parser.js:232:25)
    at Evaluator.importFile (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\evaluator.js:87:20)
    at Evaluator.visitImport (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\evaluator.js:859:27)
    at Evaluator.Visitor.visit (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\evaluator.js:157:18)
    at Evaluator.visitRoot (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\evaluator.js:673:27)
    at Evaluator.Visitor.visit (d:\hexo\node_modules\hexo-renderer-stylus\node_modules\stylus\lib\visitor\index.js:28:40)

```

**Comment by iissnan** [comment]
已经修复，谢谢反馈！对此引起的不便深感抱歉。修复详情见：https://github.com/iissnan/hexo-theme-next/commit/06a86a3ceb020f6854b5b16a84a02b274f55f1fa

**Comment by XhstormR** [comment]
thx a lot!
