### ISSUE TITLE
hexo d失败，用了很多办法都不能成功，求帮助

### ISSUE THREAD

**Issue by ljw-bigtail** [iissnan/hexo-theme-next#1322]
这是报错信息
```
$ hexo d
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
fatal: bad config line 1 in file .git/config
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                        cs/troubleshooting.html
Error: fatal: bad config line 1 in file .git/config

    at ChildProcess.<anonymous> (D:\My Blog By Hexo\node_modules\hexo-util\lib\s                        pawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\My Blog By Hexo\node_modules\cross-spawn\lib\eno                        ent.js:40:29)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
FATAL fatal: bad config line 1 in file .git/config

Error: fatal: bad config line 1 in file .git/config

    at ChildProcess.<anonymous> (D:\My Blog By Hexo\node_modules\hexo-util\lib\s                        pawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (D:\My Blog By Hexo\node_modules\cross-spawn\lib\eno                        ent.js:40:29)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
请问这个应该怎么解决？谢谢。

**Comment by ljw-bigtail** [comment]
@iissnan ，求帮助

**Comment by aixiu** [comment]
@ljw-bigtail My Blog By Hexo  去掉这目录的空格式式。

**Comment by ljw-bigtail** [comment]
谢谢，我去试一下

**Comment by iissnan** [comment]
文件 `.git/config` 报错说明你的项目内的 Git 配置有问题，你可以用编辑器打开这个文件，看里面的内容是否有有误。
