### ISSUE TITLE
Travis CI 网站自动编译不成功

### ISSUE THREAD

**Issue by ixiusama** [iissnan/hexo-theme-next#1348]
### Expected behavior (预期行为)

Travis CI 网站自动编译不成功

### Actual behavior (实际行为)

提示错误如下
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: cq
```

### Steps to reproduce the behavior (重现步骤)

只知道这个 block 是next的一个模块 想知道要如何才能解决这个问题呢？

```
$ node --version
v7.3.0
$ npm --version
3.10.10
$ nvm --version
0.32.0
hexo 3.0
```

**Comment by ixiusama** [comment]
完整错误信息如下
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: cq
    at Object.exports.prettifyError (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/environment.js:327:21)
    at /home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/hexo/post.js:253:16)
    at /home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL (unknown path) [Line 1, Column 2]
  unknown block tag: cq
Template render error: (unknown path) [Line 1, Column 2]
  unknown block tag: cq
    at Object.exports.prettifyError (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/nunjucks/src/environment.js:327:21)
    at /home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/hexo/post.js:253:16)
    at /home/travis/build/ixiusama/ixiusama.github.io/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/travis/build/ixiusama/ixiusama.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by ixiusama** [comment]
BTW 我使用的就是 NEXT 主题 ，在本地编译正常但是上 Travis CI 以后就报错了

**Comment by geekrainy** [comment]
插件的问题，cp 是标签插件。类似 `{% cp %}` 会被 hexo 注册为标签。你应该使用了此标签但是标签无法解析的原因，不是 NeXT 主题的问题。

**Comment by ixiusama** [comment]
解决了 我 fork 了一个next 主题 然后从fork上的进行编译 就解决了 应该是我改了一下 next  主题导致的吧。先睡觉先起来弄个博文来写一下过程吧
