### ISSUE TITLE
在本地部署成功，在git d时出现错误要怎么解决？错误贴在下面了

### ISSUE THREAD

**Issue by hyhang** [iissnan/hexo-theme-next#1380]
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
fatal: bad numeric config value 'flase' for 'core.autocrlf': invalid unit
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: fatal: bad numeric config value 'flase' for 'core.autocrlf': invalid unit

    at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\hyhang.github.io\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\hyhang.github.io\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
FATAL fatal: bad numeric config value 'flase' for 'core.autocrlf': invalid unit

Error: fatal: bad numeric config value 'flase' for 'core.autocrlf': invalid unit

    at ChildProcess.<anonymous> (C:\Users\Administrator\Desktop\hyhang.github.io\node_modules\hexo-util\lib\spawn.js:37:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\hyhang.github.io\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by Neveryu** [comment]
你好，你先看下这篇 [Hexo-NexT搭建个人博客（四）](https://neveryu.github.io/2016/12/15/hexo-next-four/)
看下看完以后，能不能类似解决。
