### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1480]
### Steps to reproduce the behavior (重现步骤)
```
$ hexo g
ERROR Script load failed: themes\next\scripts\tags\exturl.js
Error: Cannot find module 'hexo-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (D:\myblog-hexo\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\myblog-hexo\themes\next\scripts\tags\exturl.js:7:12
    at D:\myblog-hexo\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\myblog-hexo\node_modules\hexo\node_modules\bluebird\js\rel
ease\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\myblog-hexo\node_modules\hexo\node_
modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\myblog-hexo\node_modules\hexo\node_modules\blu
ebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\myblog-hexo\node_modules\hexo\node_modules\bl
uebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\myblog-hexo\node_modules\hexo\node_modules\bl
uebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\myblog-hexo\node_modules\hexo\node_modules\bluebird\
js\release\promise.js:628:18)
    at Promise._resolveCallback (D:\myblog-hexo\node_modules\hexo\node_modules\b
luebird\js\release\promise.js:423:57)
    at Promise._settlePromiseFromHandler (D:\myblog-hexo\node_modules\hexo\node_
modules\bluebird\js\release\promise.js:514:17)
    at Promise._settlePromise (D:\myblog-hexo\node_modules\hexo\node_modules\blu
ebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\myblog-hexo\node_modules\hexo\node_modules\bl
uebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\myblog-hexo\node_modules\hexo\node_modules\bl
uebird\js\release\promise.js:683:18)
    at Promise._fulfill (D:\myblog-hexo\node_modules\hexo\node_modules\bluebird\
js\release\promise.js:628:18)
    at D:\myblog-hexo\node_modules\hexo\node_modules\bluebird\js\release\nodebac
k.js:42:21
    at D:\myblog-hexo\node_modules\hexo\node_modules\hexo-fs\node_modules\gracef
ul-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
[Hexo-NexT搭建个人博客（四） ](https://neveryu.github.io/2016/12/15/hexo-next-four/)

参照这篇文章解决

**Comment by aixiu** [comment]
@Neveryu 谢谢你给的提示！~
```
$ npm install -- save-dev hexo-util
/
> hexo-util@0.6.0 postinstall D:\myblog-hexo\node_modules\hexo-util
> npm run build:highlight


> hexo-util@0.6.0 build:highlight D:\myblog-hexo\node_modules\hexo-util
> node scripts/build_highlight_alias.js > highlight_alias.json

save-dev@2.0.0 node_modules\save-dev

hexo-util@0.6.0 node_modules\hexo-util
├── html-entities@1.2.0
├── striptags@2.2.1
├── bluebird@3.4.7
├── highlight.js@9.9.0
├── cross-spawn@4.0.2 (lru-cache@4.0.2, which@1.2.12)
└── camel-case@3.0.0 (upper-case@1.1.3, no-case@2.3.1)
```
重新安装模块后，hexo clean  hexo d 等操作都不会报错了！~！~

**Comment by yuzhiping** [comment]
@aixiu 参照你给出的方法完美解决，多谢

**Comment by iissnan** [comment]
Refer to https://github.com/iissnan/hexo-theme-next/issues/1490

**Comment by jetyu** [comment]
thank you, make it!

**Comment by Thomas-lee-2014** [comment]
Thanks！！！

**Comment by charsdavy** [comment]
@aixiu thanks

**Comment by AlphaGao1993** [comment]
@aixiu aligado

**Comment by dogabner** [comment]
@aixiu  thanks! it works

**Comment by junbinchencn** [comment]
@aixiu thanks! it works!

**Comment by daiyongya** [comment]
perfectly solved

**Comment by wangwangchen** [comment]
nice

**Comment by miniLV** [comment]
@aixiu thanks!had resolved

**Comment by duomu** [comment]
@aixiu ,thanks very much
