### ISSUE TITLE
ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by roojay520** [iissnan/hexo-theme-next#1491]
同一个问题出现两次了  第一次重新装主题解决 请问这个问题该如何彻底解决？
>ERROR Asset render failed: css/main.css
Error: D:/blog/blog/themes/next/source/css/_common/components/highlight/highligh          t.styl:78:30
   74|
   75|   .gutter pre {
   76|     padding-left: 10px
   77|     padding-right: 10px
   78|     color: $highlight-gutter.color
------------------------------------^
   79|     text-align: right
   80|     background-color: $highlight-gutter.bg-color
   81|   }

**Comment by iissnan** [comment]
升级下 `hexo-renderer-stylus` 插件试试。

**Comment by ivan-nginx** [comment]
@roojay520 issue is solved?

**Comment by liguanghe** [comment]
遇到同样的问题:
ERROR Asset render failed: css/main.css
Error: /Users/liguanghe/liguanghe.github.io/themes/next/source/css/_common/components/highlight/highlight.styl:78:30
   74|
   75|   .gutter pre {
   76|     padding-left: 10px
   77|     padding-right: 10px
   78|     color: $highlight-gutter.color
------------------------------------^
   79|     text-align: right
   80|     background-color: $highlight-gutter.bg-color
   81|   }

hexo -- version
hexo: 3.3.6
hexo-cli: 1.0.2
os: Darwin 16.5.0 darwin x64
http_parser: 2.7.0
node: 6.10.1
v8: 5.1.281.95
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

之前安装 atom 和 algolia  , 遇到: [hexo shows error message · Issue #1055 · hexojs/hexo](https://github.com/hexojs/hexo/issues/1055)
$  npm install hexo --no-optional
之后还是安装不了, 再之后就遇到了这个问题. 
请问要如何解决?

**Comment by ukle** [comment]
反馈一下，我是在打开了baiduShare的时候出现了这个错误baidushare: truetype: slide

**Comment by feilongfl** [comment]
同样的问题
```
$ hexo --version
hexo: 3.4.0
hexo-cli: 1.0.4
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 6.8.0
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

```
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: D:/caucbb-blog/source/next/source/css/_common/components/highlight/highlight.styl:79:30
   75|
   76|   .gutter pre {
   77|     padding-left: 10px
   78|     padding-right: 10px
   79|     color: $highlight-gutter.color
------------------------------------^
   80|     text-align: right
   81|     background-color: $highlight-gutter.bg-color
   82|   }

$highlight-gutter has no property .color
    at ".gutter pre " (D:/caucbb-blog/source/next/source/css/_common/components/highlight/highlight.styl:75:4)
    at ".highlight " (D:/caucbb-blog/source/next/source/css/_common/components/highlight/highlight.styl:39:2)

    at Evaluator.visitMember (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:351:11)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitGroup (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:261:22)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitGroup (D:\caucbb-blog\node_modules\stylus\lib\visitor\evaluator.js:261:22)

```
试过`npm update hexo-renderer-stylus`，仍然没有解决，next是git安装，位于master分支

**Comment by luojiego** [comment]
我更换了hexo主目录的_config.yml文件之后，就OK了，但是我没有准确找到到底是那个配置项导致的。

**Comment by weikeqin** [comment]
```log
hexo -v
hexo-cli: 3.1.0
os: Darwin 17.7.0 darwin x64
node: 12.16.3
v8: 7.8.279.23-node.35
uv: 1.34.2
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
```

```log
18:17:21.367 ERROR Asset render failed: css/main.css
/Users/weikeqin1/WorkSpaces/blogs/blog/node_modules/stylus/lib/functions/index.styl:14:63
   10| // require a color
   11|
   12| require-color(color)
   13|   unless color is a 'color'
   14|     error('RGB or HSL value expected, got a ' + -string(color))
---------------------------------------------------------------------^
   15|
   16| // require a unit
   17|

RGB or HSL value expected, got a literal  #F0F0F0;
```

**Comment by weikeqin** [comment]
> ```
> hexo -v
> hexo-cli: 3.1.0
> os: Darwin 17.7.0 darwin x64
> node: 12.16.3
> v8: 7.8.279.23-node.35
> uv: 1.34.2
> zlib: 1.2.11
> brotli: 1.0.7
> ares: 1.16.0
> modules: 72
> nghttp2: 1.40.0
> napi: 5
> llhttp: 2.0.4
> http_parser: 2.9.3
> openssl: 1.1.1g
> cldr: 36.0
> icu: 65.1
> tz: 2019c
> unicode: 12.1
> ```
> 
> ```
> 18:17:21.367 ERROR Asset render failed: css/main.css
> /Users/weikeqin1/WorkSpaces/blogs/blog/node_modules/stylus/lib/functions/index.styl:14:63
>    10| // require a color
>    11|
>    12| require-color(color)
>    13|   unless color is a 'color'
>    14|     error('RGB or HSL value expected, got a ' + -string(color))
> ---------------------------------------------------------------------^
>    15|
>    16| // require a unit
>    17|
> 
> RGB or HSL value expected, got a literal  #F0F0F0;
> ```

i use https://github.com/theme-next/hexo-theme-next  master branch is ok 
i slove it but do't know why
