### ISSUE TITLE
更新到5.1版本报错

### ISSUE THREAD

**Issue by ifgyong** [iissnan/hexo-theme-next#1516]
error:
`ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 281, column 22:
    scroll_to_more: false
                         ^
    at generateError (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/js-yaml/lib/js-yaml/loader.js:1066:9)
    at composeNode (/Users/Jerry/Desktop/hexoDemo/hexogithub/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)`

**Comment by iissnan** [comment]
_config.yml 
YAMLException: duplicated mapping key at **line 281**, column 22:
**scroll_to_more: false**

**Comment by ifgyong** [comment]
这个地方怎么改都报错。

**Comment by iissnan** [comment]
delete this line.

**Comment by ivan-nginx** [comment]
@ifgyong solved?
