### ISSUE TITLE
hexo g报错，请教是否文章长度有限制？

### ISSUE THREAD

**Issue by iterryzhao** [iissnan/hexo-theme-next#1566]
### Expected behavior (预期行为)
hexo g正常是能够生成文件顺利通过的

### Actual behavior (实际行为)
但是新弄了一篇长篇文章之后，hexo g报错。
错误信息：

`
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
FATAL (unknown path)
  SyntaxError: Invalid or unexpected token
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/terryzhao/Documents/WebProjects/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/terryzhao/Documents/WebProjects/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/terryzhao/Documents/WebProjects/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)`
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔ Mist
  -  Pisces

**Comment by zhangnew** [comment]
大兄弟，Hexo 报错，你来这里问不合适吧。

**Comment by iissnan** [comment]
Try default theme to check if the issue was introduced by NexT.

**Comment by iterryzhao** [comment]
@zhangnew :)

@iissnan 解决咯，Thanks.

**Comment by zhuhao528** [comment]
怎么解决的
