### ISSUE TITLE
5.1.0使用algolia搜索问题

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1571]
### Expected behavior (预期行为)

点击搜索弹出搜索交互界面
### Actual behavior (实际行为)

点击搜索无反应
### Steps to reproduce the behavior (重现步骤)

提示：Algolia Settings are invalid.

配置：站点配置文件
algolia:
  appId: UGXXXXXX1X
  apiKey: 39daa80dbXXXXXXXXXXX223736
  adminApiKey: ec9212XXXXXXXXXXX2a3072XXXXXXX1
  indexName: ChaXXXXXXXg
  chunkSize: 5000
  fields:
    - title
    - slug
    - content: strip

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by charsdavy** [comment]
解决了

**Comment by kitianFresh** [comment]
如何解决的?

**Comment by micorochio** [comment]
@kitianFresh  我也刚遇到，去界面调试的时候，发现
`algolia:
  aplicationId: 
  apiKey: 
  adminApiKey: 
  indexName: 
  chunkSize: 5000`
都空了

我去Next内的_config.yml
加上了配置，就好了。

**Comment by kitianFresh** [comment]
站点配置和Next都要加吗? 我都加了还是不行, 然后只在 Next主题配置文件里面加, `hexo algolia` 就报错.
`Unhandled rejection AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (/home/kinny/Study/hexo/blog/node_modules/algoliasearch/src/AlgoliaSearchCore.js:51:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (/home/kinny/Study/hexo/blog/node_modules/algoliasearch/src/AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (/home/kinny/Study/hexo/blog/node_modules/algoliasearch/src/server/builds/AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (/home/kinny/Study/hexo/blog/node_modules/algoliasearch/src/server/builds/node.js:79:23)
    at algoliasearch (/home/kinny/Study/hexo/blog/node_modules/algoliasearch/src/server/builds/node.js:68:10)
    at /home/kinny/Study/hexo/blog/node_modules/hexo-algolia/lib/command.js:60:20
    at tryCatcher (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kinny/Study/hexo/blog/node_modules/bluebird/js/release/async.js:17:14)`
