### ISSUE TITLE
将scheme设置为Mist时,hexo g 报错

### ISSUE THREAD

**Issue by strugglingxingf** [iissnan/hexo-theme-next#1622]
error log:
Unhandled rejection Error: ENOENT: no such file or directory, open 'E:\hexo_blogs\themes\next\layout\_scripts\schemes\.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.ret.load (E:\hexo_blogs\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at compileFile (E:\hexo_blogs\node_modules\swig\lib\swig.js:695:31)
    at Object.eval [as tpl] (eval at <anonymous> (E:\hexo_blogs\node_modules\swig\lib\swig.js:498:13), <anonymous>:332:18)
    at compiled (E:\hexo_blogs\node_modules\swig\lib\swig.js:619:18)
    at _compiled (E:\hexo_blogs\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (E:\hexo_blogs\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\hexo_blogs\node_modules\hexo\lib\hexo\index.js:388:25
    at tryCatcher (E:\hexo_blogs\node_modules\bluebird\js\release\util.js:16:23)
    at E:\hexo_blogs\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\hexo_blogs\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Acris** [comment]
检查下`E:\hexo_blogs\themes\next\layout_scripts\schemes.swig`文件是否存在。

**Comment by ivan-nginx** [comment]
@strugglingxingf `layout_scripts` — this path is not exists.
