### ISSUE TITLE
升级到5.1.1，无论是默认的配置文件，还是之前可用的配置文件，hexo g均出现Unhandled rejection Error: ENOENT

### ISSUE THREAD

**Issue by GeminiGuy** [iissnan/hexo-theme-next#1675]
### Expected behavior (预期行为)
升级到5.1.1版本后，默认的配置文件都没有改动

### Actual behavior (实际行为)
hexo clean
hexo g 直接报错 无论是默认的配置文件，还是之前的配置文件均如此，
用YAML Lint测试配置文件，应该不是格式错误

Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/lixing/blog/themes/hexo-theme-next/layout/_scripts/schemes/.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.ret.load (/Users/lixing/blog/node_modules/swig/lib/loaders/filesystem.js:55:15)
    at compileFile (/Users/lixing/blog/node_modules/swig/lib/swig.js:695:31)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/lixing/blog/node_modules/swig/lib/swig.js:498:13), <anonymous>:341:18)
    at compiled (/Users/lixing/blog/node_modules/swig/lib/swig.js:619:18)
    at _compiled (/Users/lixing/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/lixing/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/lixing/blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/lixing/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/lixing/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/lixing/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

ERROR Asset render failed: css/main.css
Error: /Users/lixing/blog/themes/hexo-theme-next/source/css/_common/components/highlight/highlight.styl:78:30
   74| 
   75|   .gutter pre {
   76|     padding-left: 10px
   77|     padding-right: 10px
   78|     color: $highlight-gutter.color
------------------------------------^
   79|     text-align: right
   80|     background-color: $highlight-gutter.bg-color
   81|   }

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
执行这个命令的时候，要在项目根目录下，初步看出你的路径可能不对。

或者说是：你的某个目录名字有问题，请仔细检查一下。

:cn:

**Comment by Alexllen** [comment]
请问你这个问题怎么解决的  我卡死在这个地方解决不了
