### ISSUE TITLE
使用百度统计设置hm.js?{{id}}后无法启动

### ISSUE THREAD

**Issue by xiurierye** [iissnan/hexo-theme-next#1793]
当设置主题配置文件的  baidu_analytics：{{id}}后 
hexo g 报下面这个错误错误 
>Unhandled rejection Error: ENOENT: no such file or directory, open '{{Path2Hero}}/themes/next/layout/_scripts/schemes/.swig'

我看了下 这个目录下的文件 ，应该是 让next 自动 执行一段命令 吧 百度统计的 代码 嵌套到 我的发布站点里面吧 ，
问问 如何解决 ，以下是 debug 信息：

>Unhandled rejection Error: ENOENT: no such file or directory, open ' {{Path2Hero}}/themes/next/layout/_scripts/schemes/.swig'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.ret.load ( {{Path2Hero}}/node_modules/swig/lib/loaders/filesystem.js:55:15)
    at exports.Swig.compileFile ( {{Path2Hero}}/node_modules/swig/lib/swig.js:695:31)
    at Object.eval [as tpl] (eval at precompile ( {{Path2Hero}}/node_modules/swig/lib/swig.js:498:13), <anonymous>:337:18)

谢谢

**Comment by ivan-nginx** [comment]
@xiurierye in English, please.

**Comment by liszd** [comment]
@xiurierye 应该是你的配置出问题了
