### ISSUE TITLE
Next主题下，新建的post文章报错？

### ISSUE THREAD

**Issue by YanHuiLi** [iissnan/hexo-theme-next#1794]
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do                                                                                                                cs/troubleshooting.html
Template render error: (unknown path) [Line 206, Column 20]
  expected variable end
    at Object.exports.prettifyError (D:\Hexo\node_modules\hexo\node_modules\nunj                                                                                                                ucks\src\lib.js:34:15)
    at Obj.extend.render (D:\Hexo\node_modules\hexo\node_modules\nunjucks\src\en                                                                                                                vironment.js:469:27)
    at Obj.extend.renderString (D:\Hexo\node_modules\hexo\node_modules\nunjucks\                                                                                                                src\environment.js:327:21)
    at D:\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\rele                                                                                                                ase\debuggability.js:299:9)
    at Promise._resolveFromExecutor (D:\Hexo\node_modules\hexo\node_modules\blue                                                                                                                bird\js\release\promise.js:481:18)
    at new Promise (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\p                                                                                                                romise.js:77:14)
    at Tag.render (D:\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\Hexo\node_modules\hexo\lib\hexo\pos                                                                                                                t.js:253:16)
    at D:\Hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\ut                                                                                                                il.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Hexo\node_modules\hexo\node_modules                                                                                                                \bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Hexo\node_modules\hexo\node_modules\bluebird\j                                                                                                                s\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Hexo\node_modules\hexo\node_modules\bluebird\                                                                                                                js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Hexo\node_modules\hexo\node_modules\bluebird\                                                                                                                js\release\promise.js:691:18)
    at Async._drainQueue (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\rel                                                                                                                ease\async.js:138:16)
    at Async._drainQueues (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\re                                                                                                                lease\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Hexo\node_modules\hexo\                                                                                                                node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 206, Column 20]
  expected variable end
Template render error: (unknown path) [Line 206, Column 20]
  expected variable end
    at Object.exports.prettifyError (D:\Hexo\node_modules\hexo\node_modules\nunj                                                                                                                ucks\src\lib.js:34:15)
    at Obj.extend.render (D:\Hexo\node_modules\hexo\node_modules\nunjucks\src\en                                                                                                                vironment.js:469:27)
    at Obj.extend.renderString (D:\Hexo\node_modules\hexo\node_modules\nunjucks\                                                                                                                src\environment.js:327:21)
    at D:\Hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\rele                                                                                                                ase\debuggability.js:299:9)
    at Promise._resolveFromExecutor (D:\Hexo\node_modules\hexo\node_modules\blue                                                                                                                bird\js\release\promise.js:481:18)
    at new Promise (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\p                                                                                                                romise.js:77:14)
    at Tag.render (D:\Hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\Hexo\node_modules\hexo\lib\hexo\pos                                                                                                                t.js:253:16)
    at D:\Hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (D:\Hexo\node_modules\hexo\node_modules\bluebird\js\release\ut

**Comment by ivan-nginx** [comment]
@YanHuiLi in English, please.

**Comment by xiehaib** [comment]
@YanHuiLi 是不是因为在MarkDown中，有一种超链接方式为：`
[百度一下][1]
[1]: https://www.baidu.com/ "百度一下"`
所以你的`int [ ][ ] arr = {{1,2,3},{4,5},{6,7,8,9}};`可能导致问题，所以建议您用转义字符试试
`int \[ \]\[ \] arr = {{1,2,3},{4,5},{6,7,8,9}};`

**Comment by xiehaib** [comment]
My Enlish is not good, i easy to explain,YanHuiLi said:

**Comment by xiehaib** [comment]
My Enlish is not good, i easy to explain,YanHuiLi said:

**Comment by xiehaib** [comment]
@ivan-nginx 
My Enlish is not good, i easy to explain,YanHuiLi said:
He found a exception ,when he add the following content to  his post and use shell `hexo g`. This is the Hexo's bug ? 
```
* A:二维数组格式3
    - int [ ][ ] arr = {{1,2,3},{4,5},{6,7,8,9}};
* B:二维数组格式3的解释
* C:案例演示
    - 讲解格式，输出数据，并画内存图

```

And I tell him, The exception may be  because of  her code `int [ ][ ] arr = {{1,2,3},{4,5},{6,7,8,9}};`, `[][]` is the markdown Reference-style links, he can use the `\[\]\[\]`  to try.Do you think so ?

this's all

 thanks !

**Comment by YanHuiLi** [comment]
@xiehaib  我不知道哎，不过你提供的这个思路有点意思，可能真的是吧，
无论怎么说，还是相当感谢 你的回复。
thx

**Comment by ivan-nginx** [comment]
Ok, if solved, close it please. Thanks!

**Comment by xiehaib** [comment]
@YanHuiLi 我说的并不准备，而且我提供的方式也不准备，你可以直接`&#91;`和` &#93;`代替`[`和`]`，在hexo里面也有反应这个问题的。最后都是建议不要在md中出现`()[]{}`等等特殊字符。你可以参考如下链接：
http://blog.csdn.net/chwshuang/article/details/52350559
