### ISSUE TITLE
5.1.2 algolia搜索 根据教程配置失败

### ISSUE THREAD

**Issue by tanyunlin2003** [iissnan/hexo-theme-next#1805]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

站点根目录下执行 hexo algolia 来更新 Index

### Actual behavior 

$ hexo algolia
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (D:\Documents\Projects\norbread\node_modules\algoliasearch\src\AlgoliaSearchCore.js:55:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (D:\Documents\Projects\norbread\node_modules\algoliasearch\src\AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (D:\Documents\Projects\norbread\node_modules\algoliasearch\src\server\builds\AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (D:\Documents\Projects\norbread\node_modules\algoliasearch\src\server\builds\node.js:79:23)
    at algoliasearch (D:\Documents\Projects\norbread\node_modules\algoliasearch\src\server\builds\node.js:68:10)
    at Hexo.module.exports (D:\Documents\Projects\norbread\node_modules\hexo-algolia\lib\command.js:22:16)
    at Hexo.tryCatcher (D:\Documents\Projects\norbread\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at D:\Documents\Projects\norbread\node_modules\hexo\lib\hexo\index.js:195:9
    at Promise._execute (D:\Documents\Projects\norbread\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (D:\Documents\Projects\norbread\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\Documents\Projects\norbread\node_modules\bluebird\js\release\promise.js:79:10)
    at Hexo.call (D:\Documents\Projects\norbread\node_modules\hexo\lib\hexo\index.js:191:10)
    at C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:66:17
    at tryCatcher (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\谈XX\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:17:14)

### Steps to reproduce the behavior 

algolia:
  applicationID: 'K**'
  apiKey: 'f**a'
  adminApiKey: 'f**b'
  indexName: 'n**d'
  chunkSize: 5000

### NexT Information

**NexT Version:**

```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[x] Muse
[ ] Mist
[ ] Pisces
```

### Other Information 
![qq 20170808163346](https://user-images.githubusercontent.com/25031013/29063190-60b49f02-7c57-11e7-9579-b99acf1b8cd6.jpg)

**Comment by ivan-nginx** [comment]
@tanyunlin2003 u use `hexo algolia` in terminal. This issues for theme Next, not for Algolia.
