### ISSUE TITLE
这是什么样的报错？

### ISSUE THREAD

**Issue by David-Wey** [iissnan/hexo-theme-next#1816]
root@iZ2ze91onljhs6xkwk5onfZ:/home/wwwroot/default/note# hexo g
INFO  Start processing
ERROR Process failed: _posts/choose.md
Error
    at generateError (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/home/wwwroot/default/note/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at parseYAML (/home/wwwroot/default/note/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/wwwroot/default/note/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at /home/wwwroot/default/note/node_modules/hexo/lib/plugins/processor/post.js:52:18
    at tryCatcher (/home/wwwroot/default/note/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/home/wwwroot/default/note/node_modules/bluebird/js/release/promise.js:566:21)

**Comment by AlynxZhou** [comment]
跟你那个md内容有关？建议你检查下那个文件的yaml文件头是不是有问题。

**Comment by ivan-nginx** [comment]
@David-Wey issue solved?

**Comment by Neveryu** [comment]
`ERROR Process failed: _posts/choose.md`
这个文件有问题呀，去掉这个文件再看看。

**Comment by David-Wey** [comment]
solved
