### ISSUE TITLE
Algolia Search error/说啥lib 文件下啥啥错了

### ISSUE THREAD

**Issue by JERE-MIAH** [iissnan/hexo-theme-next#1877]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Algolia can be used.

### Actual behavior 
Actually there still some issues.

### Steps to reproduce the behavior 
1. I have already use hexo clean
2. I reinstalled with the cmd: npm install --save hexo-algolia
3. I even used cmd: hexo g 

* Link to demo site with this issue:
_PS E:\git\blog> _hexo algolia
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'filter' of undefined
    at getFields (E:\git\blog\node_modules\hexo-algoliasearch\lib\algolia.js:146:16)
    at Hexo.algolia (E:\git\blog\node_modules\hexo-algoliasearch\lib\algolia.js:16:16)
    at Hexo.tryCatcher (E:\git\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\
bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at E:\git\blog\node_modules\hexo\lib\hexo\index.js:195:9
    at Promise._execute (E:\git\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (E:\git\blog\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (E:\git\blog\node_modules\bluebird\js\release\promise.js:79:10)
    at Hexo.call (E:\git\blog\node_modules\hexo\lib\hexo\index.js:191:10)
    at C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:66:17
    at tryCatcher (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:
23)
    at Promise._settlePromiseFromHandler (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird
\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release
\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\releas
e\promise.js:614:10)
    at Promise._settlePromises (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\releas
e\promise.js:693:18)
    at Async._drainQueue (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\asyn
c.js:133:16)
    at Async._drainQueues (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\asy
nc.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\ldk62\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\re
lease\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)*_

### NexT Information

**NexT Version:** 5.1.2

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

### Other Information 
![1](https://user-images.githubusercontent.com/27946117/30510765-f7576508-9a7e-11e7-9073-b88b971f7ab9.png)

**Comment by ivan-nginx** [comment]
So? This maybe Algolia bug? Can u try another (standart) theme on Hexo?

**Comment by JERE-MIAH** [comment]
I have already solved this problem after read this plug-in's readme.md

**Comment by JERE-MIAH** [comment]
But there is another problem exist，when I click it on my blog, there will a little circle always rotate

**Comment by ivan-nginx** [comment]
I see. Can u please to work with your settings before create issues any u want? Thank's.
