### ISSUE TITLE
关于5.1.2版本使用Gulp优化问题

### ISSUE THREAD

**Issue by newdee** [iissnan/hexo-theme-next#1912]
I use the Next Mist theme(version 5.1.2),  and I use the Gulp to compress the blog files. It works on the html, css and image, but failed on the JS, the error is:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/home/newdee/Blog/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/home/newdee/Blog/node_modules/lodash/_apply.js:16:25)
    at wrapper (/home/newdee/Blog/node_modules/lodash/_createCurry.js:41:12)
    at /home/newdee/Blog/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/home/newdee/Blog/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/home/newdee/Blog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/newdee/Blog/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/newdee/Blog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/newdee/Blog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/newdee/Blog/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at write (/home/newdee/Blog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/newdee/Blog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/newdee/Blog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at emitReadable_ (/home/newdee/Blog/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
```
I have read the same issue about version 5.1.0, but it doesn't work~

**Comment by Acris** [comment]
Work fine with me. This is my gulpfile: https://github.com/Acris/blog/blob/master/gulpfile.js

**Comment by Neveryu** [comment]
haha,the same with me.but i soloved it.
the key is find error place.
so you should:
```
gulp.task('minify-js', function() {
	return gulp.src('public/js/**/*.js')
		.pipe(uglify().on('error', function(e){
			console.log(e)
		}))
		.pipe(gulp.dest('public/js'));
});
```
the core is `console.log(e)` , cross this, you will find error place and soloved it. 
trust me.

the complete file : [https://github.com/Neveryu/Neveryu.github.io/blob/resource/gulpfile.js](https://github.com/Neveryu/Neveryu.github.io/blob/resource/gulpfile.js)

**Comment by newdee** [comment]
@Acris @Neveryu Thanks， I have solved it. The problem is that gulp cannot support ES6, so I use the babel function to solove it. The solution is on [here](https://newdee.cf)

**Comment by ivan-nginx** [comment]
@newdee solved, but not closed. Thank's to u too!
