### ISSUE TITLE
Fatal Error: Unhandled rejection TypeError: path.substring is not a function

### ISSUE THREAD

**Issue by LEAFERx** [iissnan/hexo-theme-next#1918]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
errors when i run hexo s
```
Unhandled rejection TypeError: path.substring is not a function
    at Object.urlForHelper (C:\temp\blog\node_modules\_hexo@3.3.9@hexo\lib\plugi
ns\helper\url_for.js:9:31)
    at wrapper (C:\temp\blog\node_modules\_lodash@4.17.4@lodash\lodash.js:4968:1
9)
    at Object.eval [as tpl] (eval at <anonymous> (C:\temp\blog\node_modules\_swi
g@1.4.2@swig\lib\swig.js:498:13), <anonymous>:125:119)
    at compiled (C:\temp\blog\node_modules\_swig@1.4.2@swig\lib\swig.js:619:18)
    at Object.eval [as tpl] (eval at <anonymous> (C:\temp\blog\node_modules\_swi
g@1.4.2@swig\lib\swig.js:498:13), <anonymous>:797:121)
    at compiled (C:\temp\blog\node_modules\_swig@1.4.2@swig\lib\swig.js:619:18)
    at _compiled (C:\temp\blog\node_modules\_hexo@3.3.9@hexo\lib\theme\view.js:1
27:30)
    at View.render (C:\temp\blog\node_modules\_hexo@3.3.9@hexo\lib\theme\view.js
:29:15)
    at C:\temp\blog\node_modules\_hexo@3.3.9@hexo\lib\hexo\index.js:390:25
    at tryCatcher (C:\temp\blog\node_modules\_bluebird@3.5.0@bluebird\js\release
\util.js:16:23)
    at C:\temp\blog\node_modules\_bluebird@3.5.0@bluebird\js\release\method.js:1
5:34
    at RouteStream._read (C:\temp\blog\node_modules\_hexo@3.3.9@hexo\lib\hexo\ro
uter.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

* Link(s) to source code or any usefull link(s): 
I find the only file to use path.substring is sourse/src/js/utils.js
https://github.com/iissnan/hexo-theme-next/blob/master/source/js/src/utils.js#L203

### Hexo Information

```
hexo-cli: 1.0.2
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by LEAFERx** [comment]
Well it works right suddenly.
I'm not sure what I've done, and I think it's my own problem.
So close the issue.
