### ISSUE TITLE
After installing next theme and running "hexo server", I get the multiple error message

### ISSUE THREAD

**Issue by anthonyallams** [iissnan/hexo-theme-next#1962]
After installing next theme and running "hexo server", I get the following error message:

Error: /Users/client2/blog/source/_posts/themes/themes/next/source/css/_common/components/highlight/highlight.styl:79:30
   75| 
   76|   .gutter pre {
   77|     padding-left: 10px
   78|     padding-right: 10px
   79|     color: $highlight-gutter.color
------------------------------------^
   80|     text-align: right
   81|     background-color: $highlight-gutter.bg-color
   82|   }

$highlight-gutter has no property .color
    at ".gutter pre " (/Users/client2/blog/source/_posts/themes/themes/next/source/css/_common/components/highlight/highlight.styl:75:4)
    at ".highlight " (/Users/client2/blog/source/_posts/themes/themes/next/source/css/_common/components/highlight/highlight.styl:39:2)

    at Evaluator.visitMember (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:351:11)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitProperty (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:687:22)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitBlock (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitGroup (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:261:22)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitBlock (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at Evaluator.Visitor.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitGroup (/Users/client2/blog/node_modules/stylus/lib/visitor/evaluator.js:261:22)

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?

**Comment by Neveryu** [comment]
reinstall the package

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
