### ISSUE TITLE
"hexo s" prompts YAMLException: bad indentation of a mapping entry

### ISSUE THREAD

**Issue by p18r** [iissnan/hexo-theme-next#1999]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The 'Hexo s' would have no errors

### Actual behavior 
The 'Hexo s' have errors:
YAMLException: bad indentation of a mapping entry at line 122, column 3:
      GitHub: https://github.com/you| ... 
      ^
    at generateError (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
    at composeNode (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/name/Github/Hexo/xxx.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Hexo.yamlHelper (/Users/name/Github/Hexo/xxx.github.io/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/name/Github/Hexo/xxx.github.io/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/name/Github/Hexo/xxx.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

### Steps to reproduce the behavior 
1. open ~/themes/next/_config.yml
2. Remove the '#' from the line #GitHub: https://github.com/yourname || github
3. save the file
4. Hexo s
5. Error prompts.

But if we still comment the line, it works.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

git clone https://github.com/iissnan/hexo-theme-next themes/next by 2017.11.16

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by Holmeyoung** [comment]
I have the same problem,and don't know what to do...

**Comment by zhuzhuyule** [comment]
plase check your posts !

-  step. 1
Backup your posts.
-  step. 2
Delete all post.
- step. 3
Copy one post into `.\source\_posts\`
-  step. 4
Run command `hexo s`
- step. 5
  - if running is OK,  execute step.3 .
  - else checking this post or show here !

----
<div align="right">:triangular_flag_on_post:Use <a href="https://github.com/zhuzhuyule/HexoEditor">HexoEditor</a> edit</div>

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
