### ISSUE TITLE
_config.yml语法正确，但在新建文章时报YAMLException

### ISSUE THREAD

**Issue by bz51** [iissnan/hexo-theme-next#2091]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
使用hexo new post命令创建博客

### Actual behavior 
我确认_config.yml语法正确，但报如下错误：
```bash
➜  blog git:(master) ✗ hexo new post "design-pattern"
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 5, column 1:

    ^
    at generateError (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1046:9)
    at composeNode (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at /Users/chibozhou/Documents/blog/node_modules/hexo/lib/hexo/post.js:122:18
    at tryCatcher (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/chibozhou/Documents/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

_config.yml内容如下：
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 大闲人柴毛毛
subtitle:
description: 大闲人柴毛毛的博客
author: 柴毛毛
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Darwin 16.5.0 darwin x64
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
