### ISSUE TITLE
wordpress migration

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [iissnan/hexo-theme-next#2113]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.5.0
hexo-cli: 1.0.4
os: Linux 4.13.0-36-generic linux x64
http_parser: 2.7.0
node: 6.11.4
v8: 5.1.281.108
uv: 1.9.1
zlib: 1.2.11
ares: 1.13.0
icu: 57.1
modules: 48
openssl: 1.0.2g

```

### NexT Information

**NexT Version:**

```
v5.1.4
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
```
$ hexo migrate wordpress https://exports.files.wordpress.com/2018/03/longliveandprosperblog-wordpress-com-2018-03-03-12_25_43-enw6dmht0rtyrxsw6ge4gx4axxhzrbam.zip
INFO  Analyzing https://exports.files.wordpress.com/2018/03/longliveandprosperblog-wordpress-com-2018-03-03-12_25_43-enw6dmht0rtyrxsw6ge4gx4axxhzrbam.zip...
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: P
    at error (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/node_modules/sax/lib/sax.js:642:8)
    at strictFail (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/node_modules/sax/lib/sax.js:934:11)
    at Parser.exports.Parser.Parser.parseString (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/lib/xml2js.js:398:31)
    at Parser.parseString (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/lib/xml2js.js:6:61)
    at Object.exports.parseString (/home/wm/Playground/BuildABlogSite/node_modules/xml2js/lib/xml2js.js:428:19)
    at async.waterfall.count (/home/wm/Playground/BuildABlogSite/node_modules/hexo-migrator-wordpress/index.js:43:14)
    at fn (/home/wm/Playground/BuildABlogSite/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:638:34)
    at Immediate.<anonymous> (/home/wm/Playground/BuildABlogSite/node_modules/hexo-migrator-wordpress/node_modules/async/lib/async.js:554:34)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
