### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DemonsIT** [iissnan/hexo-theme-next#2178]
Unhandled rejection Error: ENOENT: no such file or directory, open 'E:\Blog\themes\n                           ext\layout\_scripts\schemes\.swig'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.ret.load (E:\Blog\node_modules\swig-templates\lib\loaders\filesystem.j                           s:59:15)
    at exports.Swig.compileFile (E:\Blog\node_modules\swig-templates\lib\swig.js:740                           :31)
    at Object.eval [as tpl] (eval at precompile (E:\Blog\node_modules\swig-templates                           \lib\swig.js:537:13), <anonymous>:904:18)
    at compiled (E:\Blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiled.locals [as _compiled] (E:\Blog\node_modules\hexo\l                           ib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:30:                           15)
    at route.set (E:\Blog\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
INFO  Catch you later

**Comment by DemonsIT** [comment]
please help me to solve the problem,thanks a lot

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
