### ISSUE TITLE
ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by Hikohikoyan** [iissnan/hexo-theme-next#2189]
看过相关问题 更新了$ npm update hexo-renderer-stylu仍然存在问题
检查了路径 和config的设置 应该也没有问题 吧？可是还是只显示框架没有css (初始hexo theme也存在渲染不出css的问题（诶所以应该去hexo那问吗 唔
```
$ hexo server
INFO  Start processing
WARN  ===============================================================
WARN  ========================= ATTENTION! ==========================
WARN  ===============================================================
WARN   NexT repository is moving here: https://github.com/theme-next
WARN  ===============================================================
WARN   It's rebase to v6.0.0 and future maintenance will resume there
WARN  ===============================================================
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Asset render failed: css/main.css
Error: D:\xampp\htdocs\learningcode\[Blog]\themes\next\source\css\main.styl:45:26
   41|
   42|
   43| // Custom Layer
   44| // --------------------------------------------------
   45| @import "_custom/custom";
--------------------------------^
   46|

failed to locate @import file D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\functions.styl

    at Evaluator.visitImport (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\evaluator.js:915:21)
    at Evaluator.Visitor.visit (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.evaluate (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (D:\xampp\htdocs\learningcode\[Blog]\node_modules\stylus\lib\renderer.js:86:26)
    at Hexo.module.exports (D:\xampp\htdocs\learningcode\[Blog]\node_modules\hexo-renderer-stylus\lib\renderer.js:53:6)
    at Hexo.tryCatcher (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\Hikoyan\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (D:\xampp\htdocs\learningcode\[Blog]\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\xampp\htdocs\learningcode\[Blog]\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
```
config：
```
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://github.com/theme-next
theme: next

```

请问是哪里设置错了吗？

**Comment by stevenjoezhang** [comment]
检查一下`_custom/custom.styl`
欢迎使用新版：https://github.com/theme-next/hexo-theme-next

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
