### ISSUE TITLE
what's the problem of this? I checked, it's not the problem of _config.yml. thanks very much!

### ISSUE THREAD

**Issue by AugF** [iissnan/hexo-theme-next#2224]
INFO  Start processing
ERROR Process failed: layout/node_modules/_concat-map@0.0.1@concat-map/README.markdown
YAMLException: end of the stream or a document separator is expected at line 17, column 44:
     ... x % 2 ? [ x - 0.1, x, x + 0.1 ] : [];
                                         ^
    at generateError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readDocument (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1539:5)
    at loadDocuments (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at Theme._View.View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\view.js:12:42)
    at new Theme._View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:37:13)
    at Theme.setView (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:71:16)
    at C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:643:18)
    at C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\hikk\Documents\blog\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Process failed: layout/node_modules/_source-map-resolve@0.5.2@source-map-resolve/readme.md
YAMLException: end of the stream or a document separator is expected at line 21, column 11:
      //   map: {file: "foo.js", mappings: ".. ...
              ^
    at generateError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readDocument (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1539:5)
    at loadDocuments (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at Theme._View.View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\view.js:12:42)
    at new Theme._View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:37:13)
    at Theme.setView (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:71:16)
    at C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:643:18)
    at C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\hikk\Documents\blog\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERROR Process failed: layout/node_modules/_source-map@0.5.7@source-map/README.md
YAMLException: tag suffix cannot contain flow indicator characters at line 3, column 9:
    [![Build Status](https://travis-ci.org/m ...
            ^
    at generateError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at readTagProperty (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1200:7)
    at composeNode (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1325:12)
    at readFlowCollection (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:735:5)
    at composeNode (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1360:11)
    at readBlockMapping (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1036:16)
    at composeNode (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1359:12)
    at readDocument (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1519:3)
    at loadDocuments (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1575:5)
    at Object.load (C:\Users\hikk\Documents\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1596:19)
    at parseYAML (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:80:21)
    at parse (C:\Users\hikk\Documents\blog\node_modules\hexo-front-matter\lib\front_matter.js:56:12)
    at Theme._View.View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\view.js:12:42)
    at new Theme._View.View (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:37:13)
    at Theme.setView (C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\index.js:71:16)
    at C:\Users\hikk\Documents\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\hikk\Documents\blog\node_modules\bluebird\js\release\promise.js:699:18)

**Comment by stevenjoezhang** [comment]
THIS REPO IS NOT SUPPORTED ANYMORE!
DON'T NEED CREATE ISSUE HERE!
NEXT MOVED HERE: https://github.com/theme-next/hexo-theme-next

NexT is rebased into organization repo https://github.com/theme-next
If you want new feature, fix, or support, create new issue in NexT v6.x repo (desirable in English).

There is instructions
on English: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md
or Chinese: https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md
how to update from v5.1.x to v 6.x

You also may read this for details: #2061

该工程已不再提供任何支持与维护！
请大家不要再在这里创建issue了！
NexT主题仓库已移动到此处: https://github.com/theme-next/hexo-theme-next

NexT已经rebase到theme-next组织(https://github.com/theme-next) 的repo中.
如果你想要求新的特性，bug修复或其他支持，请在新的v6.x的仓库下创建新issue（最好用英文，谢谢）

英文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)
或中文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md)
如何从 v5.1.x 更新到 v 6.x

相关细节参考这里: #2061
