### ISSUE TITLE
generate deploy error

### ISSUE THREAD

**Issue by phenfun** [iissnan/hexo-theme-next#296]
ERROR Asset render failed: css/main.css
Error: /Users/John/blog/themes/next/source/css/main.styl:41:57
   37| 
   38| 
   39| // Fonts
   40| @import "_common/_fonts/icon-font";
   41| @import "_common/_fonts/icon-" + hexo-config('icon_font');
---------------------------------------------------------------^
   42| 
   43| 
   44| // Vendors

failed to locate @import file _common/_fonts/icon-.styl

    at Evaluator.visitImport (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:897:21)
    at Evaluator.Visitor.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.visitRoot (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:689:27)
    at Evaluator.Visitor.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.evaluate (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:229:15)
    at Renderer.render (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/Users/John/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:45:6)
    at Hexo.tryCatcher (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.ret (eval at <anonymous> (/usr/local/lib/node_modules/hexo/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /Users/John/blog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
ERROR Asset render failed: css/main.css
Error: /Users/John/blog/themes/next/source/css/main.styl:41:57
   37| 
   38| 
   39| // Fonts
   40| @import "_common/_fonts/icon-font";
   41| @import "_common/_fonts/icon-" + hexo-config('icon_font');
---------------------------------------------------------------^
   42| 
   43| 
   44| // Vendors

failed to locate @import file _common/_fonts/icon-.styl

    at Evaluator.visitImport (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:897:21)
    at Evaluator.Visitor.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.visitRoot (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:689:27)
    at Evaluator.Visitor.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:153:18)
    at Evaluator.evaluate (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:229:15)
    at Renderer.render (/Users/John/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/Users/John/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:45:6)
    at Hexo.tryCatcher (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.ret (eval at <anonymous> (/usr/local/lib/node_modules/hexo/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /Users/John/blog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/John/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by Renlong-Yin** [comment]
从提示来看是 `_common/_fonts/icon-.styl` 文件丢失

**Comment by iissnan** [comment]
主题配置文件中 Icon fonts 设定是否有修改？

```
# Icon fonts
# Place your font into next/source/fonts, specify directory-name and font-name here
# Avialable: default | linecons | fifty-shades | feather
icon_font: default
#icon_font: fifty-shades
#icon_font: feather
#icon_font: linecons
```

**Comment by phenfun** [comment]
@Renlong-Yin 
@iissnan 
首先感谢你们热心的回复！_common/_fonts/ 目录下没有 icon-.styl 文件，全部都是以 icon-为前缀的 .styl 文件，比如：icon-font.styl。主题文件中的 Icon fonts 设定是默认的。我也不清楚怎么改好的。原先我的配置文件就有双引号之类的错误，然后我把报错位置的双引号去掉，接着就是这个错误，我好像重命名了一个文件，具体原来文件名是啥名，不记得了。贴一下 _common/_fonts/ 目录下的所有文件列表，供参考：icon-default.styl、icon-feather.styl、icon-fifty-shades.styl、icon-font.styl、icon-linecons.styl、main.styl
