### ISSUE TITLE
生成标签云之后，仍然是Cannot GET /tags/

### ISSUE THREAD

**Issue by apophise** [iissnan/hexo-theme-next#380]
生成标签云之后，仍然是Cannot GET /tags/

https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E6%A0%87%E7%AD%BE%E4%BA%91%E9%A1%B5%E9%9D%A2

我按照标准的标签云生成，然后tags文件下还是没有index.html

**Comment by matt-oconnell** [comment]
`hexo new page "tags"`

**Comment by huguangju** [comment]
加上`type: "tags"`会报错：  

```
8:08:03.086 ERROR Process failed: _posts/tags.md
TypeError: Cannot read property 'offset' of null
    at Object.exports.timezone (/Users/hugo/programming/other/blog/node_modules/hexo/lib/plugins/processor/common.js:43:40)
    at /Users/hugo/programming/other/blog/node_modules/hexo/lib/plugins/processor/post.js:118:40
    at tryCatcher (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/promise.js:505:31)
    at Promise._settlePromiseAt (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/hugo/programming/other/blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by abc123lzq** [comment]
添加一个 分类 页面，并在菜单中显示页面链接。

新建一个页面，命名为 categories 。命令如下：

hexo new page categories
编辑刚新建的页面，将页面的类型设置为 categories ，主题将自动为这个页面显示所有分类。

title: 分类
date: 2014-12-22 12:39:04
type: "categories"
---
注意：如果有启用多说 或者 Disqus 评论，默认页面也会带有评论。需要关闭的话，请添加字段 comments 并将值设置为 false，如：

title: 分类
date: 2014-12-22 12:39:04
type: "categories"
comments: false
---
在菜单中添加链接。编辑主题的 _config.yml ，将 menu 中的 categories: /categories 注释去掉，如下:

menu:
  home: /
  categories: /categories
  archives: /archives
  tags: /tags

**Comment by abc123lzq** [comment]
添加一个标签云页面，并在菜单中显示页面链接。

新建一个页面，命名为 tags 。命令如下：

hexo new page "tags"
编辑刚新建的页面，将页面的类型设置为 tags ，主题将自动为这个页面显示标签云。

title: All tags
date: 2014-12-22 12:39:04
type: "tags"
---
注意：如果有启用多说 或者 Disqus 评论，默认页面也会带有评论。需要关闭的话，请添加字段 comments 并将值设置为 false，如：

title: All tags
date: 2014-12-22 12:39:04
type: "tags"
comments: false
---
在菜单中添加链接。编辑主题的 _config.yml ，添加 tags 到 menu 中，如下:

menu:
  home: /
  archives: /archives
  tags: /tags

**Comment by JohnTian** [comment]
@abc123lzq thanks a lot.

**Comment by youglin** [comment]
按要求操作后还是Cannot GET /categories/为什么。。有大神可以解决下吗

**Comment by GodVampire** [comment]
I Use Version hexo: 3.5.0
I tried this work

/tags/index.md
`
type: "tags"`


/categories/index.md
`
type: "categories"`

**Comment by Guciliang** [comment]
解决了吗？
