### ISSUE TITLE
[error] TypeError: undefined is not a function

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#468]
[error] TypeError: undefined is not a function
TypeError: undefined is not a function
    at Hexo.<anonymous> (/Users/lee/blog/themes/next/scripts/merge-configs.js:8:26)
    at Hexo.emit (events.js:104:17)
    at module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/console/generate.js:25:8)
    at Domain.<anonymous> (/usr/local/lib/node_modules/hexo/lib/core/index.js:227:7)
    at Domain.run (domain.js:197:16)
    at Hexo.call (/usr/local/lib/node_modules/hexo/lib/core/index.js:226:7)
    at /usr/local/lib/node_modules/hexo/lib/init.js:64:10
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:154:25
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:251:17
    at /usr/local/lib/node_modules/hexo/node_modules/async/lib/async.js:154:25

lichaodeMacBook-Pro:blog lee$ hexo --version
hexo: 2.8.3
os: Darwin 14.5.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

默认主题使用没有问题，next使用的最新版本，主题的配置文件默认，站点配置文件只修改了主题。

**Comment by taoyuanxiaoqi** [comment]
hexo s --debug  运行并无问题

**Comment by iissnan** [comment]
试试在这个文件 `themes/hexo-theme-next/scripts/merge-configs.js` 头部加入：

```js
var hexo = require('hexo');
```

参考 #388

**Comment by taoyuanxiaoqi** [comment]
@iissnan 感谢回复
试了下确实可以运行了 但是还是有报错：
lichaodeMacBook-Pro:blog lee$ hexo g
[error] HexoError: Script load failed: merge-configs.js
Error: Cannot find module 'hexo'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lee/blog/themes/next/scripts/merge-configs.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by taoyuanxiaoqi** [comment]
@iissnan 但是还是有文件生成 最后 hexo s 也会报一下类似的错误 浏览器里面看效果却没什么问题

**Comment by iissnan** [comment]
或者，将刚才那句去掉，更改原先的代码为：

```js
hexo.on('generateBefore', function () {
  if (hexo.locals.get) {
    var data = hexo.locals.get('data');
    data && data.next && assign(hexo.theme.config, data.next);
  }
});
```

我现在没有 Hexo 2.8 的环境，麻烦你试下是否能解决你的问题。

**Comment by taoyuanxiaoqi** [comment]
@iissnan 这样的解法 完全可用 非常感谢！

**Comment by iissnan** [comment]
OK，多谢测试。我将这个修改放在 master 分支里。

**Comment by iissnan** [comment]
已修正这个问题。不过我建议还是升级 Hexo 到 3 。
