### ISSUE TITLE
 ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by yangzongjie** [iissnan/hexo-theme-next#564]
谢谢博主的主题,太美辣
但是我在尝试用pisces的时候出了点问题.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Schemes
scheme: Pisces(或者pisces)
debug都会报错
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR Asset render failed: css/main.css
Error: /Users/hijack/Develop/yangzongjie.github.io/hexo/themes/pisces/source/css/main.styl:14:27
   10| 
   11| // Variables Layer
   12| // --------------------------------------------------
   13| for $variable in $variables
   14|   @import "_variables/" + $variable
---------------------------------^
   15| 
   16| 
   17| // Mixins Layer

failed to locate @import file _variables/Pisces.styl

    at Evaluator.visitImport (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:901:21)
    at Evaluator.Visitor.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitBlock (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:706:39)
    at Evaluator.Visitor.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at visitBody (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:419:17)
    at Evaluator.visitEach (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:435:7)
    at Evaluator.Visitor.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitRoot (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:693:27)
    at Evaluator.Visitor.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.evaluate (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/visitor/evaluator.js:233:15)
    at Renderer.render (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/hexo-renderer-stylus/lib/renderer.js:46:6)
    at Hexo.tryCatcher (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.ret (eval at <anonymous> (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/hijack/Develop/yangzongjie.github.io/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
求博主大大指点指点

**Comment by yangzongjie** [comment]
e, 原来下错分支了...
