### ISSUE TITLE
部署时无法生成静态文件是怎么回事？

### ISSUE THREAD

**Issue by fittiger** [iissnan/hexo-theme-next#579]
报了以下错误。
root@snake:/home/snake/blog# hexo g -d
ERROR Process failed: _posts/第一篇博客.md
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 1:
    
    ^
    at generateError (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readBlockMapping (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1029:9)
    at composeNode (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1317:12)
    at readDocument (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1480:3)
    at loadDocuments (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1536:5)
    at Object.load (/home/snake/blog/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1553:19)
    at parseYAML (/home/snake/blog/node_modules/hexo/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/snake/blog/node_modules/hexo/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at /home/snake/blog/node_modules/hexo/lib/plugins/processor/post.js:87:16
    at tryCatcher (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:505:31)
    at Promise._settlePromiseAt (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/snake/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

请大家帮忙看下。

**Comment by fittiger** [comment]
应该是我的tag标签没有设置的原因吧。
