### ISSUE TITLE
更新最新版本后，generate 时报错 Unhandled rejection TypeError: str must be a string!

### ISSUE THREAD

**Issue by duchengyao** [iissnan/hexo-theme-next#619]
pull了最新版，处理了几个conflict，然后就不能用了>_<

我把conflict的文件全部还原成orig，还是提示如下错误

    Unhandled rejection TypeError: str must be a string!
    at module.exports (/Users/*****************/node_modules/hexo/node_modules/hexo-util/lib/strip_html.js:7:38)
    at Object.openGraphHelper (/Users/*****************/node_modules/hexo/lib/plugins/helper/open_graph.js:46:19)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/*****************/node_modules/hexo/node_modules/swig/lib/swig.js:498:13), <anonymous>:105:131)
    at compiled (/Users/*****************/node_modules/hexo/node_modules/swig/lib/swig.js:619:18)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/*****************/node_modules/hexo/node_modules/swig/lib/swig.js:498:13), <anonymous>:518:128)
    at compiled (/Users/*****************/node_modules/hexo/node_modules/swig/lib/swig.js:619:18)
    at Object.render (/Users/*****************/node_modules/hexo/node_modules/swig/lib/swig.js:525:41)
    at Hexo.swigRenderer (/Users/*****************/node_modules/hexo/lib/plugins/renderer/swig.js:35:15)
    at Hexo.tryCatcher (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/*****************/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/*****************/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by duchengyao** [comment]
发现错误了－ 0- 跟主题无关
