### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by yuxiaofei93** [iissnan/hexo-theme-next#691]
在运行 hexo s --debug 后遇到如下错误提示：

```
14:40:10.369 ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/home/yxf/project/hexo-blog/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/home/yxf/project/hexo-blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/home/yxf/project/hexo-blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/home/yxf/project/hexo-blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /home/yxf/project/hexo-blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /home/yxf/project/hexo-blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/yxf/project/hexo-blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:268:14
    at /home/yxf/project/hexo-blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/yxf/project/hexo-blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/yxf/project/hexo-blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:42:10
    at Object.oncomplete (fs.js:107:15)
```

**Comment by iissnan** [comment]
Fixed.
