### ISSUE TITLE
请问这个错误是？

### ISSUE THREAD

**Issue by LeoiOS** [iissnan/hexo-theme-next#761]
````node
bogon:hexo Leo$ hexo g
INFO  Start processing
ERROR Process failed: layout/_scripts/bootstrap/.gitkeep
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/Leo/Documents/hexo/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/Leo/Documents/hexo/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/Leo/Documents/hexo/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/Leo/Documents/hexo/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/Leo/Documents/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/Leo/Documents/hexo/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/Leo/Documents/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/Leo/Documents/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Files loaded in 925 ms
INFO  Generated: README.html
````

**Comment by LeoiOS** [comment]
另请问下下一个 release 大概啥时候发布？

**Comment by iissnan** [comment]
第一个问题，更新下主题。
第二个问题，我还在 Sidebar 文章目录超出的问题( #570 , #629, #734 ) 中挣扎。

**Comment by LeoiOS** [comment]
好吧，希望早点发布这个 release，我换了台电脑，暂时懒得弄了等下一个 release。。
