### ISSUE TITLE
next是否有人做成farbox主题？可行性怎样？

### ISSUE THREAD

**Issue by hanjilai** [iissnan/hexo-theme-next#849]
可能对我这个纯小白而言，Hexo的部署仍嫌复杂，经常出错。并且我想一台电脑上创建两个博客，而实际操作中却遇到各种部署问题，相比之下farbox会容易很多。
但个人又非常喜欢Next这个主题，是否有人把它改为farbox适用了呢？如果没有，那自己改的话，是否会很复杂呢

**Comment by 1354092549** [comment]
个人认为hexo部署起来还是很简单的
npm安装一下hexo，然后hexo init下，改下配置文件就行
（我本来就是node.js用户，如果没安装node.js的话，那也就多一步：安装node.js）

**Comment by panzhitian** [comment]
#####Hexo 博客的神器——Hexo 懒人携带版
https://www.v2ex.com/t/267892
https://github.com/Bitmoe/PortableHexo

**Comment by hanjilai** [comment]
@panzhitian 
之前deploy遇到的问题，使用懒人携带版后仍然会遇到，如
`at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)`

**Comment by panzhitian** [comment]
@hanjilai 你贴个完整的log看下

**Comment by hanjilai** [comment]
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\environment.js:326:21)
    at C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:16:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
FATAL (unknown path)
  SyntaxError: Unexpected token ILLEGAL
Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\lib.js:34:15)
    at Obj.extend.render (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\environment.js:468:27)
    at Obj.extend.renderString (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\nunjucks\src\environment.js:326:21)
    at C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:474:18)
    at new Promise (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\hexo\lib\hexo\render.js:63:19
    at tryCatcher (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\PortableHexo-1.0.0Released-64bit-7z\blog\node_modules\bluebird\js\release\async.js:16:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
warning: LF will be replaced by CRLF in 2016/04/27/hello-world/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in 2016/04/27/test/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in CNAME.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2016/04/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/2016/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in archives/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in css/fonts/fontawesome-webfont.svg.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in css/style.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-buttons.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-buttons.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-media.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-thumbs.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/helpers/jquery.fancybox-thumbs.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in fancybox/jquery.fancybox.pack.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in js/script.js.
The file will have its original line endings in your working directory.
On branch master
nothing to commit, working directory clean
Branch master set up to track remote branch master from https://icerice@github.com/icerice/icerice.github.io.git.
Everything up-to-date
INFO  Deploy done: git
本脚本由 Bitmoe Inc. 编写并提供技术支持！


再次配置后，弹出了库的密码窗口，输入密码后可以deploy成功，但post文档却并未更新

**Comment by panzhitian** [comment]
@hanjilai 
```
Template render error: (unknown path)
SyntaxError: Unexpected token ILLEGAL
```
语法错误
用`hexo generate --debug`找下是哪个，一般是`{{ }}`用法不对

**Comment by hanjilai** [comment]
@panzhitian 请教：在_post下粘贴大量.md文档后，hexo g总是失败。尝试粘贴一两个就没这种问题。错误提示是：
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL

**Comment by panzhitian** [comment]
用二分法排查下post是否存在问题。如果都没问题，看是否数量的问题，如果是就向hexo提交issue了。

**Comment by lunring** [comment]
表示也非常希望next主题有farbox版，farbox使用起来确实非常nice，只是主题太捉急，很多主题都两年没更新过。。太小众的原因吗？

**Comment by hanjilai** [comment]
是这样。为什么farbox官方不出资找牛人定制几款主题呢？

**Comment by zongren** [comment]
farbox好贵。。

**Comment by Sunnyyoung** [comment]
我移植了一个
预览：[http://www.sunnyyoung.net](http://www.sunnyyoung.net)

**Comment by ivan-nginx** [comment]
@hanjilai dont understand u, write in English if not solved. If solved, close it please.
