### ISSUE TITLE
请问一下Rss在sidebar的图标怎么样配置才能弄出来？

### ISSUE THREAD

**Issue by nathanHS** [iissnan/hexo-theme-next#912]
好像我的电脑装feed的插件有出现问题同时请问一下这个问题该如何处理？谢谢
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/lib.js:34:15)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:161:3)
    at Obj.extend.render (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:478:15)
    at Hexo.module.exports (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/lib/generator.js:28:22)
    at Hexo.tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:57:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at new MappingPromiseArray (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:25:10)
    at map (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:152:12)
    at Function.Promise.map (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:160:12)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo/lib/hexo/index.js:334:20
    at tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
Template render error: (unknown path) [Line 7, Column 23]
  Error: Unable to call `the return value of (posts["first"])["updated"]["toISOString"]`, which is undefined or falsey
    at Object.exports.prettifyError (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/lib.js:34:15)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:161:3)
    at Obj.extend.render (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/node_modules/nunjucks/src/environment.js:478:15)
    at Hexo.module.exports (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo-generator-feed/lib/generator.js:28:22)
    at Hexo.tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:57:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at new MappingPromiseArray (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:25:10)
    at map (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:152:12)
    at Function.Promise.map (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/map.js:160:12)
    at /home/kong/Desktop/kongBlog/hexo/node_modules/hexo/lib/hexo/index.js:334:20
    at tryCatcher (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kong/Desktop/kongBlog/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by djyde** [comment]
并不是 hexo-theme-next 的问题
