### ISSUE TITLE
layout/.DS_Store 进程失败

### ISSUE THREAD

**Issue by Chanspsyid** [iissnan/hexo-theme-next#929]
### Expected behavior (预期行为)

正常编译，生成 hexo 页面

### Actual behavior (实际行为)

编译出错，但依旧生成了页面

### Steps to reproduce the behavior (重现步骤)

在 social 字段中添加了社交链接信息后，编译时出现问题

INFO  Start processing
ERROR Process failed: layout/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/WenHuaChang/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Files loaded in 1.4 s
INFO  Generated: atom.xml
INFO  Generated: 2016/06/03/Bilibili-Interface-Design-Usability-Heuristics-Colors/index.html
INFO  Generated: baidusitemap.xml
INFO  Generated: sitemap.xml
INFO  4 files generated in 890 ms

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

部署网站时，同样出现错误信息：

INFO  Start processing
ERROR Process failed: layout/.DS_Store
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/WenHuaChang/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/promise.js:629:18)
    at /Users/WenHuaChang/hexo/node_modules/hexo-fs/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/WenHuaChang/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.

请大神指教如何解决？

**Comment by Chanspsyid** [comment]
在 https://github.com/hexojs/hexo/issues/1793 找到了答案
