### ISSUE TITLE
加入“leancloud阅读次数”统计时报错

### ISSUE THREAD

**Issue by cutler** [iissnan/hexo-theme-next#977]
### Expected behavior (预期行为)
能显示阅读次数

### Actual behavior (实际行为)
Unhandled rejection Error: ENOENT: no such file or directory, open 'F:\workspace\github\blog\blog\themes\hexo-theme-next\layout\_scripts\schemes\\.swig
'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.ret.load (F:\workspace\github\blog\blog\node_modules\hexo\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at compileFile (F:\workspace\github\blog\blog\node_modules\hexo\node_modules\swig\lib\swig.js:695:31)
    at Object.eval [as tpl] (eval at <anonymous> (F:\workspace\github\blog\blog\node_modules\hexo\node_modules\swig\lib\swig.js:498:13), <anonymous>:6
26:18)
    at compiled (F:\workspace\github\blog\blog\node_modules\hexo\node_modules\swig\lib\swig.js:619:18)
    at _compiled (F:\workspace\github\blog\blog\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\workspace\github\blog\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\workspace\github\blog\blog\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (F:\workspace\github\blog\blog\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\workspace\github\blog\blog\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\workspace\github\blog\blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:733:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Master

NexT Scheme:
  -  Pisces

**Comment by bobbyliujb** [comment]
是不是重复写了leancloud_visitors

**Comment by cutler** [comment]
嗯啊，已经改完了，多谢了。
